[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]~=4.1"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version = ['py36']
quiet = true

[tool.isort]
line_length = 88
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true

[tool.setuptools_scm]
write_to = "src/nasty_typeshed/_version.py"
write_to_template = "__version__ = \"{version}\"\n"
